#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinAndroidPhotoViewer.Resource", IsApplication=true)]

namespace XamarinAndroidPhotoViewer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int wallpaper = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int extract_visible_bitmap = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int iv_photo = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int menu_matrix_capture = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int menu_matrix_restore = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int menu_scale_fit_center = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int menu_scale_fit_end = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int menu_scale_fit_start = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int menu_scale_fit_xy = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int menu_scale_random = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int menu_scale_random_animate = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int menu_scale_scale_center = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int menu_scale_scale_center_crop = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int menu_scale_scale_center_inside = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int menu_zoom_toggle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int tv_current_matrix = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
